name: CI-CD-Job
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on:
    - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.4.0
    - name: run command
      shell: bash
      run: echo ${{ github.actor }}
    - name: step3
      uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn --batch-mode --update-snapshots package
      
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: deploy
      shell: bash
      run: echo ${{ github.actor }}
