name: CI-CD-Job
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on:
      - ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3.4.0
    - name: run command
      shell: bash
      run: echo Rupesh 1
